<?php

if (system\Helper::arcIsAjaxRequest()) {
    
    $tasks = TMTask::getAllByUserID(system\Helper::arcGetUser()->id, "All");
    
    $new = "";
    $progress = "";
    $done = "";
    
    foreach ($tasks as $task) {
        if (date('Ymd') == date('Ymd', strtotime($task->donedate))) {
            $done .= "<tr><td>{$task->id}</td><td>" . html_entity_decode($task->description) . "</td><td>{$task->hours}</td></tr>";
        } elseif ($task->status == "In Progress") {
            $progress .= "<tr><td>{$task->id}</td><td>" . html_entity_decode($task->description) . "</td><td>{$task->hours}</td></tr>";
        } elseif ($task->status == "New") {
            $new .= "<tr><td>{$task->id}</td><td>" . html_entity_decode($task->description) . "</td><td>{$task->hours}</td></tr>";
        }
    }
    
    $message .= "<html><head><style>";
    $message .= "table { width: 100%; border-collapse: collapse; } table tr td { border-bottom: 1px solid #000000; } table tr th { border-bottom: 1px solid #000000; font-weight: bold; }";
    $message .= "</style></head><body>Task Report for " . system\Helper::arcGetUser()->getFullname() . " (" . date("y-m-d H:i:s") . ")";
    $message .= "<h3>Done Today</h3>";
    $message .= "<table><tr><th>#</th><th>Description</th><th>Hours</th></tr>{$done}</table>";
    $message .= "<h3>In Progress</h3>";
    $message .= "<table><tr><th>#</th><th>Description</th><th>Hours</th></tr>{$progress}</table>";
    $message .= "<h3>New</h3>";
    $message .= "<table><tr><th>#</th><th>Description</th><th>Hours</th></tr>{$new}</table></body></html>";
    
    $message .= "<p>Generated by Task Master</p>";
    
    $emailSettings = SystemSetting::getByKey("TM_SENDTOEMAILS");
    $emails = explode(",", $emailSettings->value);
    
    $mail = new Mail();
    $mail->Send($emails, "Task Report (" . system\Helper::arcGetUser()->getFullname() . ")", $message, true);
    
    system\Helper::arcAddMessage("success", "Report Sent");
}